title: triskadecaepyon
email:
description: > # this means to ignore newlines until "baseurl:"
  Software engineering in the heart of Texas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://triskadecaepyon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: triskadecaepyon
github_username:  triskadecaepyon

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
