title: triskadecaepyon
email:
description: > # this means to ignore newlines until "baseurl:"
  A collection of my work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: triskadecaepyon
github_username:  triskadecaepyon

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
